### ISSUE TITLE
issue running script

### ISSUE THREAD

**Issue by eengland** [kfiala/AviSysDataAccess#1]
Hi,

Thanks so much for providing this script, I'm hoping you can help me with where I'm having trouble. I am trying to convert my dad's files from AviSys 5. I had disk imaged the hard drive from the computer that AviSys 5 was on, and have found the data folder. I can't run the script from that actual folder because the disk image was set to read-only, so I created a copy of the data folder and put that on my desktop, and put the script in that folder. When I tried to run the script I got an error:
`(base) ElizabethsAir3:BIRDATA1 elizabethengland$ python3 SightingsTOcsv.py
Traceback (most recent call last):
  File "SightingsTOcsv.py", line 459, in <module>
    kernel32 = ctypes.WinDLL('kernel32', use_last_error=True)
AttributeError: module 'ctypes' has no attribute 'WinDLL'`

Is this because I was trying to do this on a Mac but AviSys was a Windows program? Should it work if I switch to Windows? Thanks!

**Comment by kfiala** [comment]
I do all my work on Windows, I have no idea about Mac. However, the line where you are getting the error is just a thing to determine whether the module form of the script (which you are not using) was launched by double-click vs command line. You could just comment out lines 459 and 460 and set num_processes to 3 and see if you get further.

However, you mention AviSys 5, which is from many years ago. The script is written for AviSys 6 and I don't think it will work for you. You'd need to convert the data for AviSys 6.

**Comment by kfiala** [comment]
Oops, closed accidentally, didn't mean to.

**Comment by eengland** [comment]
Ah, thanks. I edited the script as you suggested but then hit different errors for lines 
490 and 240.
Is the AviSys 6 software available anywhere? I've been browsing the website you've maintained (thank you, it's been really useful as I try to figure this out) and saw in the closing announcement that "The upgrade from Versions 4 and 5 to Version 6 will no longer be available." (http://avisys.info/closing.html). I'm not sure what to do, other than try to emulate a version of Windows compatible with AviSys 5, and see if I can open the data files in version 5 and export them that way.

**Comment by kfiala** [comment]
Those errors sound like Mac doesn't support the Windows-1252 character encoding. You could probably substitute another; plain ASCII would probably work.
Get in touch with me at Kent.Fiala@gmail.com and I can help you with AviSys 6.
